### ISSUE TITLE
Fest fails to compile with latest nightly

### ISSUE THREAD

**Issue by ghost** [fest-im/fest#11]
Fest fails to compile on the latest version of rust-nightly with an error in futures-await, possibly need to update the version of ruma-client in use, and/or ruma-client's dependancies.

**Comment by jplatte** [comment]
I'm aware of the issue. On it.

**Comment by jplatte** [comment]
So unless we use `unsafe`, this is blocked on https://github.com/alexcrichton/futures-await/issues/79 (as you seem to have figured out yourself). I'd prefer to just wait for a fix for that issue, and to keep using an older Nightly until then.

**Comment by ghost** [comment]
I've been told it's perfectly fine to use `unsafe` to fix this since it's just `futures-await` code, and they never return unmovable generators. But if you want to wait that's fine.

**Comment by jplatte** [comment]
Fixed in https://github.com/fest-im/fest/commit/863d75ead4626ffa621a917e767c65a02862944b
