### ISSUE TITLE
Builds for Windows?

### ISSUE THREAD

**Issue by ghost** [fest-im/fest#17]
I created this issue to find out if this app builds for windows, but I think this would be a decent tracking issue to have until Fest becomes functional and a maintainer comes forward. I would volunteer myself, but I have a lot to learn about programming in general before I can do so.

**Comment by her001** [comment]
At the moment, all of the contributors to Fest use Linux. We consider multiplatform support in our design decisions, which means that Windows should always work. Eventually we may have instructions for building it yourself on Windows, but I think that we will need someone who is willing to maintain Windows builds before we provide them.

Note that no builds are available for any platform right now, considering Fest is currently not functional as a chat client. You can follow the implementation status in #16.

**Comment by rogersachan** [comment]
Thanks for the reply! I created this issue to find out if this app builds for windows, but I think this would be a decent tracking issue to have until Fest becomes functional and a maintainer comes forward. I would volunteer myself, but I have a lot to learn about programming in general before I can do so.

Thanks again,

Roger

**Comment by her001** [comment]
Ah, okay. Sorry that I misunderstood the question. To clarify, I don't know if Fest builds in Windows right now, but it certainly *should*, as far as I know. I don't think anyone has ever tried.

In case anyone does want to attempt it, I'm going to leave some links here which may or may not be useful:

* [Installing GTK+ on Windows](https://www.gtk.org/download/windows.php)
* gtk-rs issue for [bundling GTK+ in Windows builds](https://github.com/gtk-rs/gtk/issues/422)
* gtk-rs tutorial for [cross-compiling Windows builds](http://gtk-rs.org/tuto/cross) (from Linux to Windows)
* [Working with Rust on Windows](https://github.com/rust-lang-nursery/rustup.rs#working-with-rust-on-windows) section of the rustup readme
