### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by yabirgb** [fest-im/fest#19]
Hi

I'm trying to compile it but I get the following error

```
yabir@heis ~/apps/fest $ cargo +nightly run
    Updating git repository `https://github.com/fest-im/ruma-events`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `ruma-events`

Caused by:
  Unable to update https://github.com/fest-im/ruma-events?branch=synapse-workarounds#f960d47b

Caused by:
  failed to clone into: /home/yabir/.cargo/git/db/ruma-events-ec6285c517fe6a7f

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

Caused by:
  failed to acquire username/password from local configuration
```

I'm not an expert with cargo but I think is something related with a missing dependency. How can I install it?

**Comment by jplatte** [comment]
Thanks for reporting this! I'm not sure why I didn't update the dependencies here when I deleted the ruma-* forks from this org. I think there was some issue, but I'm having a look at it again now.

**Comment by jplatte** [comment]
Fixed by https://github.com/fest-im/fest/commit/0b9fa5a62e46ea49df70b57683ef109b43bb326. If you want to contribute to fest, I'd suggest joining [#fest-im:matrix.org](https://matrix.to/#/#fest-im:matrix.org) :wink:

**Comment by yabirgb** [comment]
I had to install `libgtk-3-dev` and `libcairo2-dev` don't know if both are needed. Also had to add 

`cairo-rs = { version = "^0", features = ["png"] }`

to the `Cargo.toml` At least now it compiled. Don't know if i'm doing something wrong but if it's ok I can add it to the README

**Comment by jplatte** [comment]
Having to install the header files for gtk on systems that don't install them as part of the library makes sense. You can add that to the README.md as Debian + Ubuntu specific build steps. However, `libcairo2-dev` is a dependency of `libgtk-3-dev` (according to the [package db](https://packages.ubuntu.com/cosmic/libgtk-3-dev)) so you shouldn't have to install it manually. Also, you shouldn't have to add anything to `Cargo.toml`. What issue did you have that was fixed by that?

**Comment by yabirgb** [comment]
I added that to the Cargo.toml before installing the dependencies so maybe I didn't understand the error root. Thanks!
