### ISSUE TITLE
Main panics after opening directory then closing program

### ISSUE THREAD

**Issue by ghost** [fest-im/fest#9]
Main will panic if you select the login option `As Guest` then skip the first directory dialog, open the directory again from the menu (this causes a panic due to it being unimplemented), then attempt to close the client using the `x` button from the GTK window.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', libcore/result.rs:945:5`
```

**Comment by ghost** [comment]
i've just had a look at the code and this could be related to lines `100-108` at the end of `src/app/mod.rs`

**Comment by jplatte** [comment]
Yeah, that's the only `unwrap()` in our code for a `SendError` it seems. [Permalink for reference](https://github.com/fest-im/fest/blob/62d7c835bb3bcc997ced2b90ce5ba7f02ef71589/src/app/mod.rs#L105).

[The docs](https://docs.rs/futures/0.1.18/futures/sink/struct.Wait.html#method.send) aren't clear on why this error would occur, but I'd assume the channel got closed prematurely. I'll look into it.

**Comment by jplatte** [comment]
Oh, actually this is completely expected. The backend thread currently panics because it gets a command to fetch the directory for the guest user, but that is [not yet implemented](https://github.com/fest-im/fest/blob/master/src/bg_thread.rs#L158).

**Comment by ghost** [comment]
i see, i'll close this issue then since this will go away once the directory fetch is implemented and the backend doesn't panic and close the thread
